# Generated by Django 5.0.1 on 2026-07-04 12:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_airecommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airecommendation',
            name='motivation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='next_goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='strengths',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list), size=None),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='summary',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='airecommendation',
            name='weaknesses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=list), size=None),
        ),
    ]
