# Generated by Django 5.0.1 on 2026-07-02 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_airecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIRecommendation',
        ),
    ]
